name: Update portfolio

on:
  push:
    branches:
      - main

    paths:
      - "portfolio/**"

  workflow_dispatch:

jobs:
  trigger-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger portfolio publishing workflow
        env:
          GH_TOKEN: ${{ secrets.PORTFOLIO_TRIGGER_TOKEN }}

        run: |
          curl --fail-with-body \
            --request POST \
            --url "https://api.github.com/repos/mateocordobatoro/mateocordobatoro.github.io/actions/workflows/publish.yml/dispatches" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${GH_TOKEN}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --data '{"ref":"main"}'